# Change these first
owner: sage-iq # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Sage IQ
    url: https://sage-iq.com/
  - name: x-crx-dev
    url: $SECRET_SITE_CPS_DEV
  - name: x-crx-prod
    url: $SECRET_SITE_CPS_PROD
  - name: tcg
    url: $SECRET_SITE_TCG_PROD

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sage-iq.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sage IQ
  introTitle: Status Page
  introMessage: This is the [Sage IQ](https://sage-iq.com) status page.
  navbar:
    - title: Home
      href: https://sage-iq.com
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

assignees:
  - ojas

i18n:
  footer: This page is [open source]($REPO), powered by [Upptime](https://upptime.js.org)